dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
- python setup.py -q install
- pip install -r test-requirements.txt

script:
  - echo "Running Tests ..."
  - pytest -v --cov
  - flake8
  - coverage run --source=tensorflow_scientific setup.py test

after_success:
  - coveralls
  # - python setup.py sdist bdist_wheel
  # - twine upload dist/*

notifications:
  email:
    recipients:
      - mukesh@mukeshmithrakumar.com
    on_success: never
    on_failure: always
